# vim:fileencoding=utf-8:foldmethod=marker:ft=kitty

# INFO: https://github.com/knubie/vim-kitty-navigator

map ctrl+h neighboring_window left
map ctrl+j neighboring_window down
map ctrl+k neighboring_window up
map ctrl+l neighboring_window right

map --when-focus-on var:IS_VIM ctrl+h
map --when-focus-on var:IS_VIM ctrl+j
map --when-focus-on var:IS_VIM ctrl+k
map --when-focus-on var:IS_VIM ctrl+l
