#!/usr/bin/env zsh
# joopal-trim-whitespace (joopal-trim)
#   trims leading and trailing whitespace from arguments
#   INFO: https://stackoverflow.com/a/3352015/672346


function joopal-trim() {
    local var="$*"
    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var"
}


joopal-trim "$@"
