#!/usr/bin/env zsh
# joopal-trim-whitespace (trim-whitespace)
#   trims leading and trailing whitespace from arguments
#   INFO: https://stackoverflow.com/a/3352015/672346

#local v=$(echo "$*" | tr -s ' ') # remove multiple whitespaces
#v="${v#"${v%%[![:space:]]*}"}"  # remove leading whitespace characters
#v="${v%"${v##*[![:space:]]}"}"  # remove trailing whitespace characters

autoload -Uz echoer

function _trim-whitespace() {
    local v=$*
    v=$(echo "$v" | tr -s ' ' | tr -d $'\n'); v=${v%% } ; v=${v## };
    printf '%s\n' "${(p)v}"
}


function _trim-whitespace-args() {
    if [[ $# == 0 ]] { echoer "🚫 ERROR: no args, no stdin 🚫"; return 12; }
    local lines=$(echo "$*" | awk NF)
    for line (${(f)lines}) {
        _trim-whitespace "${line}"
    }
}

function _trim-whitespace-stdin() {
    local stdin=`echo "$(</dev/stdin)"`
    local lines=$(echo "$stdin" | awk NF)
    for line (${(f)lines}) {
        _trim-whitespace "${line}";
    }
}


if [[ -p /dev/stdin ]]; then
    _trim-whitespace-stdin
else
    _trim-whitespace-args "$@"
fi | head -c-1
