#!/usr/bin/env zsh
# joopal-trim-whitespace (trim-whitespace)
#   trims leading and trailing whitespace from arguments
#   INFO: https://stackoverflow.com/a/3352015/672346


autoload -Uz echoer # custom error handler of mine

function _trim-whitespace() {
    local v=$*
    v=$(echo "$v" | tr -s ' ' | tr -d $'\n'); v=${v%% } ; v=${v## };
    printf '%s\n' "${(p)v}"
}


function _trim-whitespace-args() {
    if [[ $# == 0 ]] { echoer "🚫 ERROR: no args, no stdin 🚫"; return 12; }
    local lines=$(echo "$*" | awk NF)
    for line (${(f)lines}) {
        _trim-whitespace "${line}"
    }
}

function _trim-whitespace-stdin() {
    local stdin=`echo "$(</dev/stdin)"`
    local lines=$(echo "$stdin" | awk NF)
    for line (${(f)lines}) {
        _trim-whitespace "${line}";
    }
}


(if [[ ! -t 0 ]] && [[  ! -p /dev/stdout || -p /dev/stdout ]]; then
    _trim-whitespace-stdin < /dev/stdin
else
    _trim-whitespace-args $*
fi) | head -c-1
