#!/usr/bin/env zsh
# joopal-trim-whitespace (trim-whitespace)
#   trims leading and trailing whitespace from arguments
#   INFO: https://stackoverflow.com/a/3352015/672346

function trim-whitespace() {
    autoload -Uz echoer
    if [[ ! -v 1 ]]; then
      echoer "🚫 no arguments given 🚫"
      return 12
    fi

    local var="$*"

    # remove leading whitespace characters
    var="${var#"${var%%[![:space:]]*}"}"
    # remove trailing whitespace characters
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var" | tr -s ' '
}

trim-whitespace "$@"
