#!/usr/bin/env bash
# vim: set fdm=marker:


# kitty {{{
function _() {
    if command_exists kitty; then
        kitty + complete setup "$(current_shell)" | source /dev/stdin
    fi
} && _; unset -f _
# }}}


# ipfs {{{
function _() {
    if command_exists ipfs ; then
        if [[ $OSX == "$TRUE" ]]; then
            local ipfs_bash_compl="$BREW/etc/bash_completion.d/ipfs-completion.bash"
        elif [[ $LINUX == "$TRUE" ]]; then
            local ipfs_bash_compl="$BREW/share/bash-completion/completions/ipfs"
        fi
        [[ -f $ipfs_bash_compl ]] && source "$ipfs_bash_compl"
    fi
} && _; unset -f _
# }}}
